# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('STU', 'Student'), ('STA', 'Staff'), ('FAC', 'Faculty')], default='STU', max_length=3)),
                ('pswd', models.CharField(max_length=128)),
            ],
        ),
    ]
