# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FUCK_MIGRATIONS',
            fields=[
                ('field', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
