# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0002_fuck_migrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FUCK_MIGRATIONS',
        ),
    ]
