# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 03:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VoxPomona', '0002_auto_20170418_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('STU', 'Student'), ('STA', 'Staff'), ('FAC', 'Faculty')], default='STU', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='change',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoxPomona.UserInfo', to_field='email'),
        ),
        migrations.AlterField(
            model_name='changevote',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoxPomona.UserInfo', to_field='email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoxPomona.UserInfo', to_field='email'),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoxPomona.UserInfo', to_field='email'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoxPomona.UserInfo', to_field='email'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoxPomona.UserInfo', to_field='email'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
