# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0003_auto_20170418_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='faculty_permission',
            field=models.CharField(choices=[('1', 'view'), ('2', 'view, sign'), ('3', 'view, sign, comment'), ('4', 'view, sign, comment, propose changes'), ('5', 'view, sign, comment, propose changes, modify')], default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='petition',
            name='staff_permission',
            field=models.CharField(choices=[('1', 'view'), ('2', 'view, sign'), ('3', 'view, sign, comment'), ('4', 'view, sign, comment, propose changes'), ('5', 'view, sign, comment, propose changes, modify')], default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='petition',
            name='stu_permission',
            field=models.CharField(choices=[('1', 'view'), ('2', 'view, sign'), ('3', 'view, sign, comment'), ('4', 'view, sign, comment, propose changes'), ('5', 'view, sign, comment, propose changes, modify')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='petition',
            name='category',
            field=models.CharField(choices=[('AC', 'Academics'), ('AA', 'Administrative Action'), ('DH', 'Dining Halls'), ('SR', 'School Recidency'), ('OT', 'Others')], default='AC', max_length=2),
        ),
    ]
