# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0004_auto_20170424_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='category',
            field=models.CharField(choices=[('AC', 'Academics'), ('AA', 'Administrative Action'), ('CF', 'CF'), ('CP', 'CP'), ('DH', 'Dining Halls'), ('EA', 'Extracurricular Activities'), ('RH', 'Residence Halls'), ('OT', 'Other')], max_length=2),
        ),
    ]
