# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0004_auto_20170418_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='id',
        ),
        migrations.AlterField(
            model_name='change',
            name='chid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petition',
            name='petitionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
