# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 03:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0005_auto_20170418_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='summary',
            field=models.CharField(default='A Petition', max_length=500),
        ),
        migrations.AddField(
            model_name='petition',
            name='title',
            field=models.CharField(default='New Petition', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserInfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='changevote',
            unique_together=set([('userID', 'chid')]),
        ),
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set([('userID', 'cid')]),
        ),
        migrations.AlterUniqueTogether(
            name='sign',
            unique_together=set([('userID', 'petitionID')]),
        ),
    ]
