# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0005_auto_20170425_2025'),
        ('VoxPomona', '0005_auto_20170425_2022'),
    ]

    operations = [
    ]
