# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0006_auto_20170420_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='clause',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VoxPomona.Clause'),
        ),
        migrations.AddField(
            model_name='comment',
            name='clause',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VoxPomona.Clause'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterUniqueTogether(
            name='change',
            unique_together=set([('userID', 'clause')]),
        ),
        migrations.AlterUniqueTogether(
            name='clause',
            unique_together=set([('petitionID', 'index')]),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('userID', 'clause')]),
        ),
    ]
