# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0006_merge_20170425_2049'),
        ('VoxPomona', '0006_merge_20170425_2045'),
    ]

    operations = [
    ]
