# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0007_auto_20170420_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='threshold',
        ),
        migrations.AlterField(
            model_name='change',
            name='clause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoxPomona.Clause'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='clause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoxPomona.Clause'),
        ),
    ]
