# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0007_merge_20170425_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='category',
            field=models.CharField(blank=True, choices=[('AC', 'Academics'), ('AA', 'Administrative Action'), ('CF', 'Campus Facilities'), ('CP', 'Campus Policy'), ('DH', 'Dining Halls'), ('EA', 'Extracurricular Activities'), ('RH', 'Residence Halls'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='petition',
            name='faculty_permission',
            field=models.CharField(choices=[('1', 'view'), ('2', 'view, sign'), ('3', 'view, sign, comment'), ('4', 'view, sign, comment, propose changes')], default=4, max_length=1),
        ),
        migrations.AlterField(
            model_name='petition',
            name='staff_permission',
            field=models.CharField(choices=[('1', 'view'), ('2', 'view, sign'), ('3', 'view, sign, comment'), ('4', 'view, sign, comment, propose changes')], default=4, max_length=1),
        ),
        migrations.AlterField(
            model_name='petition',
            name='stu_permission',
            field=models.CharField(choices=[('1', 'view'), ('2', 'view, sign'), ('3', 'view, sign, comment'), ('4', 'view, sign, comment, propose changes')], default=4, max_length=1),
        ),
    ]
