# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0008_auto_20170420_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clause',
            name='title',
        ),
        migrations.AlterField(
            model_name='change',
            name='content',
            field=models.CharField(default='New Change', max_length=500),
        ),
        migrations.AlterField(
            model_name='clause',
            name='content',
            field=models.CharField(default='New Clause', max_length=500),
        ),
        migrations.AlterField(
            model_name='petition',
            name='category',
            field=models.CharField(choices=[('AC', 'Academics'), ('AA', 'Administrative Action'), ('CF', 'CF'), ('CP', 'CP'), ('DH', 'Dining Halls'), ('EA', 'Extracurricular Activities'), ('RH', 'Residence Halls'), ('OT', 'Other')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='petition',
            name='summary',
            field=models.CharField(default='A Petition', max_length=1000),
        ),
    ]
