# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0009_remove_change_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='close_time',
        ),
    ]
