# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0009_auto_20170423_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([]),
        ),
    ]
