# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0010_remove_petition_close_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
