# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0010_auto_20170424_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='chid',
            new_name='changeID',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='clause',
            new_name='clauseID',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='cid',
            new_name='commentID',
        ),
        migrations.RemoveField(
            model_name='clause',
            name='id',
        ),
        migrations.AddField(
            model_name='clause',
            name='clauseID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
