# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0011_auto_20170424_2007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clause',
            unique_together=set([]),
        ),
    ]
