# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0011_petition_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='petition',
            name='open_time',
            field=models.DateTimeField(),
        ),
    ]
