# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0012_auto_20170427_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='petition',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
