# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0014_change_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='commentID',
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='userID',
        ),
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
