# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoxPomona', '0015_auto_20170430_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='faculty_permission',
            new_name='fac_permission',
        ),
        migrations.RenameField(
            model_name='petition',
            old_name='staff_permission',
            new_name='sta_permission',
        ),
    ]
